[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false
validator = "legacy"

[programs.devnet]
fbyt_clone_vault = "FJY6JUzQybrA5CbM9jgnTJtndhEU6vBAFF5vCuvq6Ais"

[programs.localnet]
fbyt_clone_vault = "FJY6JUzQybrA5CbM9jgnTJtndhEU6vBAFF5vCuvq6Ais"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
